spring.application.name=BE_Restaurant
server.port=8080
server.address=127.0.0.1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3307/restaurant?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=12345678
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
jwt.expiration=604800000
jwt.secret="sdfasdgaetgaegdfgadsfgadfgertyreujaerthe"
server.error.whitelabel.enabled=false
